//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowRoom.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Orders = new HashSet<Order>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int BrandId { get; set; }
        public int FuelTypeId { get; set; }
        public int AirId { get; set; }
        public int TypeId { get; set; }
        public double EngineCapacity { get; set; }
        public double FuelRate { get; set; }
        public int TrunkVolume { get; set; }
        public int HorsePower { get; set; }
        public int Year { get; set; }
        public int TransmissionId { get; set; }
        public int DoorCount { get; set; }
        public int ColorId { get; set; }
        public int Price { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual Air Air { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual Transmission Transmission { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
